# Generated by Django 4.1.1 on 2022-10-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Familia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familia",
            name="fecha_nacimiento",
        ),
    ]
